"""Backend-neutral simulation interfaces used by front ends and tasks."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Mapping, Protocol, Sequence, runtime_checkable

from .mujoco_types import ControlStatus, RandomizedScene, SimulationState


@runtime_checkable
class SimulationProtocol(Protocol):
    """Stable control/state surface implemented by simulation backends."""

    joint_names: tuple[str, ...]

    @property
    def timestep(self) -> float: ...

    @property
    def control_targets(self) -> tuple[float, ...]: ...

    @property
    def control_mode(self) -> str: ...

    def reset(self, seed: int | None = None) -> SimulationState: ...
    def reset_home(self, seed: int | None = None) -> SimulationState: ...
    def step(self, steps: int = 1) -> SimulationState: ...
    def get_state(self) -> SimulationState: ...
    def get_control_status(self) -> ControlStatus: ...
    def get_contacts(self): ...
    def set_mode(self, mode: str) -> str: ...
    def command_joint_positions(
        self, targets: Mapping[str, float] | Sequence[float]
    ) -> tuple[float, ...]: ...
    def command_joint_torques(
        self, torques: Sequence[float], timeout_s: float = 0.1
    ) -> tuple[float, ...]: ...
    def command_gripper_width(
        self, width_m: float, max_force_n: float | None = None
    ) -> float: ...
    def randomize_scene(self, seed: int | None = None, **kwargs) -> RandomizedScene: ...
    def close(self) -> None: ...


class RandomizationCapableSimulation(Protocol):
    def apply_randomization(self, sample) -> None: ...
    def restore_randomization(self) -> None: ...
    def randomization_session(self, sample) -> AbstractContextManager: ...
